{ pkgs, lib, unstable, ... }:

{
  home.packages = with pkgs; [
    woeusb
    gtk2
    kdePackages.partitionmanager
    protonup
    gdu
    chromium
    tor-browser
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.ark
    arduino
    typst-live
    unrar
    gnumake
    python313Packages.python-lsp-server
    qalculate-gtk
    typst
    pyright
    lua-language-server
    tinymist
    geogebra6
    komikku
    ranger
    ueberzugpp
    newsflash
    inspector
    nwg-look
    vscodium
    grayjay
    jetbrains.pycharm-community-src
    kdePackages.dolphin-plugins
    lshw
    python313Packages.ml-collections
    python313Packages.networkx
    cbonsai
    python313Packages.scipy
    kdePackages.kdenlive
    obs-studio
    gimp
    vlc
    prismlauncher
    killall
    alpaca
    qbittorrent
    matugen
    equibop
    gjs
    nitch
    wl-clipboard
    kdePackages.okular
    popsicle
    gparted
    kdePackages.gwenview
    usbutils
    glib
    libnotify
    nautilus
    alsa-utils
    heroic
    shadps4
    rpcs3
    mission-center
    wev
    onlyoffice-desktopeditors
    nixd
    freecad
    bitwarden-desktop
    libreoffice-qt6
    alacritty
    xorg.xrandr
    librewolf
    mate.mate-polkit
    swww
    fzf
    lsd
    kdePackages.dolphin
    imagemagick
    neovim
    tree
  ];
  programs.lutris.enable = true;
  programs.lutris.protonPackages = [ pkgs.proton-ge-bin ];
  services.gnome-keyring.enable = true;
}
