{ pkgs, ... }:

{
  home.packages = with pkgs; [
    woeusb
    quickshell
    noctalia-shell
    kdePackages.qtdeclarative
    neovide
    virtiofsd
    android-tools
    unityhub
    libadwaita
    spicetify-cli
    gtk2
    fortune
    kdePackages.partitionmanager
    gdu
    readest
    sigil
    adw-gtk3
    qt6Packages.qt6ct
    localsend
    brave
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.ark
    arduino
    unrar
    gnumake
    python313Packages.python-lsp-server
    qalculate-gtk
    pyright
    lua-language-server
    tinymist
    ranger
    ueberzugpp
    inspector
    nwg-look
    vscodium
    kdePackages.dolphin-plugins
    lshw
    python313Packages.ml-collections
    python313Packages.networkx
    cbonsai
    python313Packages.scipy
    kdePackages.kdenlive
    obs-studio
    gimp
    vlc
    prismlauncher
    killall
    qbittorrent
    matugen
    equibop
    gjs
    nitch
    wl-clipboard
    kdePackages.okular
    popsicle
    kdePackages.gwenview
    usbutils
    glib
    libnotify
    nautilus
    alsa-utils
    heroic
    mission-center
    wev
    onlyoffice-desktopeditors
    nixd
    bitwarden-desktop
    libreoffice-qt6
    alacritty
    xrandr
    librewolf
    mate-polkit
    awww
    fzf
    lsd
    kdePackages.dolphin
    imagemagick
    neovim
    tree
  ];
  programs.lutris.enable = false;
  programs.lutris.protonPackages = [ pkgs.proton-ge-bin ];
  services.gnome-keyring.enable = true;
}
