#!/bin/bash

# Define cache directory
CACHE_DIR="$HOME/.cache/current-wallpaper"

# Fetch the wallpaper path from swww
wallpaper_path=$(swww query | awk '{print $8}')

# Copy the wallpaper to the cache directory (if it's not already there)
cp "$wallpaper_path" "$CACHE_DIR"

