#!/bin/bash

wall=$(find ~/wallpapers/ -type f -name "*.jpg" -o -name "*.png" -o -name "*.gif" | shuf -n 1)


# Picks background wallpaper
swww img  --transition-type wipe $wall


# generate color scheme
wal -c
wal -i $wall

# Deletes the sww cache
rm -rf $HOME/.cache/swww


